# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c027dcb88a00c3761f596546f229c131f9815575e4854c87cb72ef789813531a02fce9f848b6720b94a4f86ce0b7de301fd960b019168270e425fef013900b01

test:
  secret_key_base: 4cd32d4d4491984c7074f8307d0588d23e88095d367e7682fb59a05b48db8de8a39031028fd0fd15ec5c76b782abb57376afd5f88f4893a3b15df35a45d400bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
